<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64;ARM64</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>GPOSettingsExplorer</AssemblyName>
    <RootNamespace>GPOSettingsExplorer</RootNamespace>
    <Version>0.4.3</Version>
    <FileVersion>0.4.3.0</FileVersion>
    <AssemblyVersion>0.4.3.0</AssemblyVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.0" />
  </ItemGroup>

</Project>
